networks:
  public-network:
    driver: overlay
    external: true

  private-network:
    driver: overlay
    external: true

services:
  momly_web:
    image: tanngoc93/app_momly:latest
    working_dir: /app
    volumes:
      # - "/root/momly/logs:/app/log"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    environment:
      # Rails & App
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY_MOMLY}
      RAILS_ENV: ${RAILS_ENV:-production}
      PORT: ${PORT:-3000}
      HOST: ${HOST_MOMLY}

      # Database
      DATABASE_POOL: ${DATABASE_POOL}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USER: ${POSTGRES_USER}
      DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
      DATABASE_PRODUCTION: ${DATABASE_PRODUCTION}

      # CAPTCHA
      RECAPTCHA_SITE_KEY: ${RECAPTCHA_SITE_KEY_MOMLY}
      RECAPTCHA_SECRET_KEY: ${RECAPTCHA_SECRET_KEY_MOMLY}
    command: /bin/sh "/app/.dockerdev/commander/rails.sh"
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=public-network"
        - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"

        - "traefik.http.routers.momly-http.rule=Host(`momly.me`)"
        - "traefik.http.routers.momly-http.entrypoints=web"

        - "traefik.http.routers.momly-secured.rule=Host(`momly.me`)"
        - "traefik.http.routers.momly-secured.entrypoints=websecured"
        - "traefik.http.routers.momly-secured.tls.certresolver=myhttpchallenge"

        - "traefik.http.services.momly-svc.loadbalancer.server.port=3000"
      update_config:
        parallelism: 1
        delay: 60s
        failure_action: rollback
        monitor: 10s
        order: start-first
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    stop_grace_period: 30s
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - private-network
      - public-network
