FROM ruby:3.2.3

ENV PORT=3000 \
    RAILS_ENV=development \
    BUNDLE_PATH=/bundle \
    APP_DIR=/app \
    DEBIAN_FRONTEND=noninteractive \
    ACCEPT_EULA=Y \
    TTF_MSCORE_INSTALLER_LICENSE_ACCEPTED=1

RUN apt-get update -qq \
  && apt-get install -yq --no-install-recommends \
    software-properties-common \
  && apt-add-repository contrib \
  && apt-get update -qq \
  && apt-get install -yq --no-install-recommends \
    build-essential \
    curl \
    git \
    graphviz \
  && apt-get clean \
  && rm -rf /var/cache/apt/archives/* \
  && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* \
  && truncate -s 0 /var/log/*log

RUN mkdir -p $APP_DIR $APP_DIR/log $APP_DIR/tmp/pids
RUN apt-get update -qq && apt-get install -y postgresql-client

RUN curl -fsSL https://deb.nodesource.com/setup_18.x | bash - && \
    apt-get install -y nodejs && \
    npm install -g yarn

COPY Gemfile      $APP_DIR/Gemfile
COPY Gemfile.lock $APP_DIR/Gemfile.lock

WORKDIR $APP_DIR


# Configure bundler
ENV LANG=C.UTF-8 \
  BUNDLE_JOBS=4 \
  BUNDLE_RETRY=3

# Store Bundler settings in the project's root
ENV BUNDLE_APP_CONFIG=.bundle

# Upgrade RubyGems and install latest Bundler
RUN gem update --system && \
    gem install bundler && bundle install

COPY . $APP_DIR/

# Clean up APT when done.
RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

#
EXPOSE $PORT
